### ISSUE TITLE
Used in SNP VCF

### ISSUE THREAD

**Issue by biozzq** [fritzsedlazeck/SVCollector#1]
Dear all,

Can we use this tool to select an optimal subset of samples that collectively contain the largest number of distinct variants when the input is the population SNP vcf file？ In my mind, it should be Ok. Thus, I have tried with following command (`SVCollector greedy SNP.vcf -1 20 1 result`), the output is as follows. My SNP.vcf contains about ~80,000 SNPs, I cannot understand what does the number in each column mean? 
```
Sample	#SVs	#_SVs_captured	SVs_captured
PPOOOST210163309	13830.649556	13830.649556	0.817167
YYOOOST210129913	1748.636723	15579.286278	0.920483
Y6550106371	594.960513	16174.246792	0.955635
```
Looking forward to your reply, thanks.

Sincerely yours,
Zheng zhuqing

**Comment by fritzsedlazeck** [comment]
Dear Zheng, 
yes you can. We also did try that in our paper. 

The columns are:
SAmple (sample identifier taken from the VCF file)
#SV (number of variants, the way you ran it is that variants are weighted so we don't count +1 per variant)
#_SV_captured (number of variants captured in total so far, thus first line this is the same number , 2nd sample increases it)
SVs_captured (is the ratio of all variants captured across your VCF file). 

As I mentioned we now have a newer implementation also here https://github.com/ACEnglish/utmos 

thanks
Fritz

**Comment by biozzq** [comment]
Thank you for your detailed and helpful response.
