### ISSUE TITLE
No more samples to select from

### ISSUE THREAD

**Issue by biozzq** [fritzsedlazeck/SVCollector#2]
Dear all,

When I set the number of samples to select to 100, it returns me only 15 samples and with the information (No more samples to select from), does this mean that the selected 15 samples can represent the whole genetic diversity?

Best regards,
Zheng zhuqing

**Comment by fritzsedlazeck** [comment]
Dear Zheng, 
Whats the number of samples in your input? If there is no parsing or other error that would imply that these 15 samples do cover all your variations. We recently also did a re-implementation that is faster: https://github.com/ACEnglish/utmos 

Thanks
Fritz

**Comment by biozzq** [comment]
Thank you. the input contains 876 samples and they have similar genetic backgrounds, thus it is possible that these 15 samples do cover all the variants. I will try the new tools you suggest.

Best regards,
Zheng zhuqing
